### ISSUE TITLE
Role에 따라 auth guard 설정

### ISSUE THREAD

**Issue by sanghunjo921** [sanghunjo921/ticketing-nest#33]
### 목표
User role에 따라 호출 가능한 엔드포인트에 가드를 설정합니다.

### 제약조건
- 민감한 정보를 반환하는 엔드포인트의 경우 admin role을 가진 user만 호출 가능합니다.
- 티켓에 관한 엔드포인트는 get을 제외하면 provider role을 가진 user만 호출 가능합니다.
- User는 기본적으로 consumer role을 가지고 있습니다.
- Provider role을 가진 user는 consumer role의 권한도 가지고 있습니다.
- Admin role을 가진 user는 provider와 consumer role 권한도 가지고 있습니다. 

### Task
- [x] auth guard service을 수정하여 user의 role에 따른 guard를 설정합니다.
- [x] role 정보를 key 기반으로 메타데이터를 생성하는 custom decorator를 만듭니다.
- [x] 가드가 필요한 엔드포인트에 생성한 custom decorator를 주입하니다.
- [x] User의 role을 체크하는 로직을 만듭니다.

### 통과조건 (Acceptance Criteria; AC)
- Admin role을 가진 유저가 모든 유저의 정보를 반환하는 엔드포인트를 호출하면 정상적으로 결과를 반환합니다.
- Admin role을 가지지 않은 유저가 모든 유저의 정보를 반환하는 엔드포인트를 호출하면 호출하면 UnAuthorization error를 반환합니다.
- Admin/Provider role을 가진 유저가 티켓에 대한 create/update/delete 엔드포인트를 호출하면 정상적으로 동작합니다.
- Admin/Provider role을 가지지 않은 유저가 티켓에 대한 create/update/delete 엔드포인트를 호출하면 UnAuthorization error를 반환합니다.
